# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  runnername: abc
jobs:
  first_job:
        
        
        name: first job
        #runs-on: [self-hosted, X64, Windows] # Or your specific self-hosted runner label
        runs-on: [AR3]
        outputs:
          runner_name: ${{ runner.name }}
        steps:
          - name: Set output variable
            run: echo "$runnername = ${{ runner.name }} from output" >> $GITHUB_OUTPUT
          - name: Get Runner Name
            #run: echo "Runner name is ${{ runner.name }}"
            run: echo "Runner name is $runnername"
  second_job:
        needs: first_job
        #runs-on: ${{ first_job.outputs.runner_name }}
        #runs-on: [self-hosted, "${{ needs.first_job.outputs.runner_name }}"]
        runs-on: [AR3]
        steps:
          - name: Verify Runner
            run: echo "This job is running on ${{ runner.name }}"
