# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  first_job:
        name: first job
        runs-on: [self-hosted, X64, Windows] # Or your specific self-hosted runner label
        outputs:
          runner_name: ${{ runner.name }}
        steps:
          - name: Get Runner Name
            run: echo "Runner name is ${{ runner.name }}"
  second_job:
        needs: first_job
        runs-on: ["${{ runner.name }}"]
        # runs-on: ${{ needs.first_job.outputs.runner_name }}
        steps:
          - name: Verify Runner
            run: echo "This job is running on ${{ runner.name }}"
